name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.17, 1.x]

    steps:
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ matrix.go-version }}-go-

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -yqq --no-install-recommends libsystemd-dev

    - name: Test
      run: go test -v ./...
